format = "$all"

add_newline = true

[character]
success_symbol="[\\$](bold bright-red)"
error_symbol = "[✖](bold bright-red)"

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 25
style = "bold bright-red"

[gcloud]
disabled = true

[cmd_duration]
disabled = true